<a href="https://colab.research.google.com/github/KudryashovDmitry/PDA_SOL/blob/main/%D0%9A%D1%83%D0%B4%D1%80%D1%8F%D1%88%D0%BE%D0%B2_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_3_%D1%872.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Линейная алгебра с Numpy

С помощью [Sympy](http://www.sympy.org/en/index.html) можно выполнять символьную линейную алгебру, но для числовых вычислений [Numpy](http://www.numpy.org/) является высокопроизводительная библиотека, которую следует использовать при решении математических и инженерныхзадач.

Описание:

> NumPy — это фундаментальный пакет для научных вычислений на Python. Он содержит, среди прочего: [...]
 линейную алгебру, преобразование Фурье и теорию вероятностей.

В этом разделе научимся, как:

- работать с матрицами;
- решать матричные уравнения;
- рассчитывать обратную матрицу и определители.

## Работа с матрицами

Создать матрицу с помощью Numpy несложно. В качестве примера рассмотрим следующее:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


Сначала, как и в Sympy, нам нужно импортировать Numpy:

In [14]:
import numpy as np

Теперь можем определить $A$:

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [ ]:
A

matrix([[ 1, -1],
        [ 2,  1]])

In [ ]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [ ]:
B

Можно получить как следствие:

- $5A$ (или любое другое скалярное число, кратное $A$);
- $A ^ 3$ (или любой другой показатель $A$);
- $A + B$;
- $A - B$;
- $AB$

In [ ]:
5 * A

matrix([[ 5, -5],
        [10,  5]])

In [ ]:
A ** 3

In [ ]:
A + B

In [ ]:
A - B

In [ ]:
A * B

In [ ]:
A = np.matrix([[1, -1], [2, 1]])
A

matrix([[ 1, -1],
        [ 2,  1]])

In [ ]:
A**2 - 2*A +3

matrix([[0, 3],
        [3, 0]])

---

**УПРАЖНЕНИЕ 1** Решить $A ^ 2 – 2 A + 3$ с помощью:

$$A =
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

## Решение матричных уравнений

Можно использовать Numpy для (эффективного) решения больших систем уравнений вида:

$$Ax=b$$

Проиллюстрируем это:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1
\end{pmatrix}
$$

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

Мы используем команду `linalg.solve`:

In [ ]:
x = np.linalg.solve(A, b)
x

Проверим результат:

In [ ]:
A * x

In [ ]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [ ]:
b = np.matrix([[-1], [2], [1]])

In [ ]:
x = np.linalg.solve(B, b)
x

matrix([[-0.25892857],
        [ 0.40178571],
        [ 0.28571429]])

In [ ]:
B*x

matrix([[-1.],
        [ 2.],
        [ 1.]])

---
**УПРАЖНЕНИЕ 2** Найти решение матричного уравнения $Bx=b$ (используя $B$).

---

## Обратные матрицы и определители

Найдем обратную матрицу:

In [17]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[ 0.33333333,  0.33333333],
        [-0.66666667,  0.33333333]])

Проверка $A^{-1}A=\mathbb{1}$:

In [18]:
A * Ainv

matrix([[1.00000000e+00, 5.55111512e-17],
        [0.00000000e+00, 1.00000000e+00]])

Казалось бы, что матрица не единичная, однако по главной  `1` , а на всех остальных позициях **очень** маленькие числа (однако для компьютера это `0`).

Вычислим детерминант:

In [19]:
np.linalg.det(A)

2.9999999999999996

---

**УПРАЖНЕНИЕ 2** Вычислите обратную матрицу и определитель $B$ (ранее уже находили).

---

In [15]:
Binv = np.linalg.inv(B)
Binv

matrix([[ 6.25000000e-02, -1.84523810e-01,  1.72619048e-01],
        [-6.25000000e-02,  1.36904762e-01,  6.54761905e-02],
        [-1.09511795e-17,  2.38095238e-01, -1.90476190e-01]])

In [16]:
B*Binv

matrix([[ 1.00000000e+00,  0.00000000e+00,  1.11022302e-16],
        [ 7.55253758e-19,  1.00000000e+00,  8.32667268e-17],
        [ 4.45599717e-17, -3.33066907e-16,  1.00000000e+00]])

In [20]:
np.linalg.det(B)

-336.0