<a href="https://colab.research.google.com/github/KudryashovDmitry/PDA_SOL/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [4]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

---



In [ ]:
a = np.full(7,7)
print(a)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
a=np.arange(10,101,2)
print(a)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
a=np.random.randint(1,10,size=10)
print(a)
b=np.flipud(a)
print(b)

[3 7 7 9 9 1 3 6 9 3]
[3 9 6 3 1 9 9 7 7 3]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 8

In [ ]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [13]:
a = np.eye(4, k=1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
a=np.diag(range(1,5))
a[a==0]=7
print(a)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
a=np.array(list(range(5)) * 5).reshape(5,5)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [12]:
a=np.random.randint(10,size=(10,10))
print(a)
a1 = a-a.mean(axis=1,keepdims=True)
print(a1)


[[5 4 5 7 6 0 7 1 6 5]
 [8 2 1 5 9 7 9 5 3 1]
 [1 9 4 2 0 5 0 0 5 3]
 [3 9 8 0 0 3 1 3 8 9]
 [8 5 0 2 6 0 0 8 6 6]
 [6 3 7 6 1 5 9 8 9 6]
 [2 6 7 0 8 8 3 8 3 6]
 [7 7 5 7 3 1 8 9 3 1]
 [3 0 4 1 2 6 5 1 2 7]
 [7 7 9 8 7 0 0 9 0 0]]
[[ 0.4 -0.6  0.4  2.4  1.4 -4.6  2.4 -3.6  1.4  0.4]
 [ 3.  -3.  -4.   0.   4.   2.   4.   0.  -2.  -4. ]
 [-1.9  6.1  1.1 -0.9 -2.9  2.1 -2.9 -2.9  2.1  0.1]
 [-1.4  4.6  3.6 -4.4 -4.4 -1.4 -3.4 -1.4  3.6  4.6]
 [ 3.9  0.9 -4.1 -2.1  1.9 -4.1 -4.1  3.9  1.9  1.9]
 [ 0.  -3.   1.   0.  -5.  -1.   3.   2.   3.   0. ]
 [-3.1  0.9  1.9 -5.1  2.9  2.9 -2.1  2.9 -2.1  0.9]
 [ 1.9  1.9 -0.1  1.9 -2.1 -4.1  2.9  3.9 -2.1 -4.1]
 [-0.1 -3.1  0.9 -2.1 -1.1  2.9  1.9 -2.1 -1.1  3.9]
 [ 2.3  2.3  4.3  3.3  2.3 -4.7 -4.7  4.3 -4.7 -4.7]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [11]:
a=np.random.randint(10,size =(10,10))
print(a)
a1=a-np.median(a,axis=0,keepdims=True)
print(a1)

[[4 7 0 8 2 1 3 8 4 9]
 [5 0 3 1 7 0 2 4 7 1]
 [2 0 5 8 7 0 7 0 1 9]
 [5 7 7 7 9 3 2 4 3 3]
 [3 4 1 1 7 5 8 1 5 1]
 [5 4 3 4 3 7 0 6 6 9]
 [9 5 6 6 2 2 5 8 3 0]
 [4 9 9 4 5 8 0 7 6 6]
 [9 1 9 3 8 0 2 0 9 1]
 [5 7 3 8 4 5 9 7 9 6]]
[[-1.   2.5 -4.   3.  -4.  -1.5  0.5  3.  -1.5  4.5]
 [ 0.  -4.5 -1.  -4.   1.  -2.5 -0.5 -1.   1.5 -3.5]
 [-3.  -4.5  1.   3.   1.  -2.5  4.5 -5.  -4.5  4.5]
 [ 0.   2.5  3.   2.   3.   0.5 -0.5 -1.  -2.5 -1.5]
 [-2.  -0.5 -3.  -4.   1.   2.5  5.5 -4.  -0.5 -3.5]
 [ 0.  -0.5 -1.  -1.  -3.   4.5 -2.5  1.   0.5  4.5]
 [ 4.   0.5  2.   1.  -4.  -0.5  2.5  3.  -2.5 -4.5]
 [-1.   4.5  5.  -1.  -1.   5.5 -2.5  2.   0.5  1.5]
 [ 4.  -3.5  5.  -2.   2.  -2.5 -0.5 -5.   3.5 -3.5]
 [ 0.   2.5 -1.   3.  -2.   2.5  6.5  2.   3.5  1.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [9]:
a=np.random.randint(100,size=(5, 5))
a.max(axis=1,keepdims=True)
a.min(axis=1,keepdims=True)
np.concatenate((a,a.max(axis=1,keepdims=True),a.min(axis=1,keepdims=True)),axis=1)

array([[63, 21, 11, 60, 35, 63, 11],
       [43, 16, 16, 27, 86, 86, 16],
       [45, 47, 74, 65, 48, 74, 45],
       [64,  4, 94, 59, 76, 94,  4],
       [33, 54, 61, 96, 54, 96, 33]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [6]:
a=np.mat(np.arange(1,50)[1::2]).reshape(4,6)
b=np.mat(np.arange(1,50)[2::2]).reshape(6,4)
print(a)
print(b)
print(a*b)
print(np.linalg.inv(a*b))

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]
 [38 40 42 44 46 48]]
[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]
 [35 37 39 41]
 [43 45 47 49]]
[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]
[[-3.66503876e+11  3.21853878e-04  1.09951163e+12 -7.33007752e+11]
 [-7.33007752e+11  2.19902326e+12 -2.19902326e+12  7.33007752e+11]
 [ 2.56552713e+12 -4.39804651e+12  1.09951163e+12  7.33007752e+11]
 [-1.46601550e+12  2.19902326e+12  0.00000000e+00 -7.33007752e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [14]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
